### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by zemcov** [SOFIA-USRA/sofia_redux#3]
Hi there - I'm trying to install sofia_redux on FC34.  I have installed the dependencies listed here:
https://sofia-usra.github.io/sofia_redux/sofia_redux/index.html#getting-started
(specifically in requirements.txt, optional_requirements.txt, and PyQt5).  When I try to install via:
> pip3 install . 
I get the error:
ERROR: Failed building wheel for sofia-redux
ERROR: Could not build wheels for sofia-redux which use PEP 517 and cannot be installed directly
I have appended the full output capture as a file for your inspection.  Any help would be appreciated.  
[out.log](https://github.com/SOFIA-USRA/sofia_redux/files/8565212/out.log)

**Comment by melanieclarke** [comment]
Hello!

This sounds like it might be an issue with your pip version.   I'm not sure how much I can help because you're using an installation path I haven't tried, but looking around, this solution is frequently recommended for similar problems:

pip3 install --upgrade pip setuptools wheel

If that doesn't work, please give me more information about your system, including pip and Python version, and I'll see what I can find for you.

**Comment by zemcov** [comment]
That was it!  Thanks so much for the help.

**Comment by melanieclarke** [comment]
Great!  I'm glad you're up and running!
